"""First Brillouin-zone construction from reciprocal-lattice half-spaces.

The first zone is the Wigner--Seitz cell around the reciprocal-space origin.
For every non-zero reciprocal vector ``G`` it is bounded by

``G · k <= |G|² / 2``.

The implementation deliberately keeps the geometric core dependency-free:
vertices are intersections of triples of planes, followed by a half-space
test.  This makes the construction transparent and easy to compare with the
algorithm described in the 2021 undergraduate report.
"""

from __future__ import annotations

from dataclasses import dataclass
from itertools import combinations, product
from typing import Any, Iterable, Sequence

import numpy as np

from .lattices import Lattice
from .reciprocal import reciprocal_vectors


def _basis(value: Any) -> np.ndarray:
    if isinstance(value, Lattice):
        return value.reciprocal_vectors
    array = np.asarray(value, dtype=float)
    if array.shape != (3, 3):
        raise ValueError("lattice or reciprocal_vectors must have shape (3, 3)")
    if not np.all(np.isfinite(array)):
        raise ValueError("reciprocal_vectors must contain only finite values")
    if abs(float(np.linalg.det(array))) <= np.finfo(float).eps * max(1.0, np.linalg.norm(array) ** 3):
        raise ValueError("reciprocal_vectors must be linearly independent")
    return array


def _reciprocal_candidates(basis: np.ndarray, max_index: int) -> np.ndarray:
    coefficients = np.asarray(
        list(product(range(-max_index, max_index + 1), repeat=3)), dtype=int
    )
    coefficients = coefficients[np.any(coefficients != 0, axis=1)]
    points = coefficients @ basis
    # Numerical round-off can make a pair generated by opposite indices look
    # microscopically different.  Preserve one copy of each exact vector.
    unique: dict[tuple[float, float, float], np.ndarray] = {}
    for point in points:
        key = tuple(np.round(point, decimals=13))
        unique.setdefault(key, point)
    points = np.asarray(list(unique.values()), dtype=float)
    order = np.argsort(np.linalg.norm(points, axis=1), kind="stable")
    return points[order]


def _plane_intersections(normals: np.ndarray, offsets: np.ndarray, tolerance: float) -> np.ndarray:
    """Return all triple intersections that satisfy every half-space."""

    if len(normals) < 4:
        # Three planes can still enclose a bounded cell only in degenerate
        # situations, but testing it here gives a useful empty result.
        triples: Iterable[tuple[int, int, int]] = combinations(range(len(normals)), 3)
    else:
        triples = combinations(range(len(normals)), 3)
    normal_scale = max(1.0, float(np.max(np.linalg.norm(normals, axis=1))))
    equation_tolerance = tolerance * normal_scale
    vertices: list[np.ndarray] = []
    for first, second, third in triples:
        n1, n2, n3 = normals[first], normals[second], normals[third]
        determinant = float(np.dot(n1, np.cross(n2, n3)))
        if abs(determinant) <= np.finfo(float).eps * normal_scale**3 * 100.0:
            continue
        b1, b2, b3 = offsets[first], offsets[second], offsets[third]
        point = (
            b1 * np.cross(n2, n3)
            + b2 * np.cross(n3, n1)
            + b3 * np.cross(n1, n2)
        ) / determinant
        residual = normals @ point - offsets
        if np.all(residual <= equation_tolerance):
            vertices.append(point)
    if not vertices:
        return np.empty((0, 3), dtype=float)
    array = np.asarray(vertices)
    coordinate_tolerance = tolerance * max(1.0, float(np.max(np.linalg.norm(array, axis=1))))
    # Round first for speed and then use allclose to avoid merging genuinely
    # distinct vertices when a user requests a relatively loose tolerance.
    decimals = max(0, int(np.ceil(-np.log10(max(coordinate_tolerance, 1e-14)))) + 1)
    rounded = np.round(array, decimals=decimals)
    _, unique_indices = np.unique(rounded, axis=0, return_index=True)
    unique_indices.sort()
    return array[unique_indices]


def _ordered_face(vertex_indices: Sequence[int], vertices: np.ndarray, normal: np.ndarray) -> tuple[int, ...]:
    indices = np.asarray(vertex_indices, dtype=int)
    points = vertices[indices]
    center = np.mean(points, axis=0)
    unit_normal = normal / np.linalg.norm(normal)
    reference = np.array([1.0, 0.0, 0.0])
    if abs(float(np.dot(reference, unit_normal))) > 0.85:
        reference = np.array([0.0, 1.0, 0.0])
    first_axis = np.cross(unit_normal, reference)
    first_axis /= np.linalg.norm(first_axis)
    second_axis = np.cross(unit_normal, first_axis)
    relative = points - center
    angles = np.arctan2(relative @ second_axis, relative @ first_axis)
    ordered = indices[np.argsort(angles)]
    if len(ordered) >= 3:
        edge_a = vertices[ordered[1]] - vertices[ordered[0]]
        edge_b = vertices[ordered[2]] - vertices[ordered[1]]
        if np.dot(np.cross(edge_a, edge_b), unit_normal) < 0:
            ordered = ordered[::-1]
    return tuple(int(index) for index in ordered)


def _facets(
    normals: np.ndarray, offsets: np.ndarray, vertices: np.ndarray, tolerance: float
) -> tuple[np.ndarray, tuple[tuple[int, ...], ...]]:
    scale = max(1.0, float(np.max(np.linalg.norm(normals, axis=1))))
    plane_tolerance = tolerance * scale
    active_normals: list[np.ndarray] = []
    faces: list[tuple[int, ...]] = []
    for normal, offset in zip(normals, offsets):
        distances = np.abs(vertices @ normal - offset)
        on_plane = np.flatnonzero(distances <= plane_tolerance)
        if len(on_plane) < 3:
            continue
        points = vertices[on_plane]
        if np.linalg.matrix_rank(points[1:] - points[0], tol=plane_tolerance) < 2:
            continue
        active_normals.append(normal)
        faces.append(_ordered_face(on_plane, vertices, normal))
    if not faces:
        raise RuntimeError("could not identify Brillouin-zone facets")
    return np.asarray(active_normals), tuple(faces)


def _edges_from_faces(faces: Sequence[Sequence[int]]) -> tuple[tuple[int, int], ...]:
    edges: set[tuple[int, int]] = set()
    for face in faces:
        for first, second in zip(face, (*face[1:], face[0])):
            edges.add(tuple(sorted((int(first), int(second)))))
    return tuple(sorted(edges))


def _construct_zone(reciprocal_basis: np.ndarray, normals: np.ndarray, tolerance: float) -> "BrillouinZone":
    """Construct a zone for an already selected set of reciprocal vectors."""

    offsets = 0.5 * np.einsum("ij,ij->i", normals, normals)
    vertices = _plane_intersections(normals, offsets, tolerance)
    if len(vertices) < 4:
        raise RuntimeError(
            "could not construct a bounded first Brillouin zone; "
            "increase search for a highly anisotropic lattice"
        )
    facet_vectors, faces = _facets(normals, offsets, vertices, tolerance)
    active_offsets = 0.5 * np.einsum("ij,ij->i", facet_vectors, facet_vectors)
    halfspaces = np.column_stack((facet_vectors, -active_offsets))
    return BrillouinZone(
        reciprocal_vectors=reciprocal_basis,
        vertices=vertices,
        faces=faces,
        edges=_edges_from_faces(faces),
        halfspaces=halfspaces,
        facet_vectors=facet_vectors,
    )


@dataclass(frozen=True)
class BrillouinZone:
    """Convex polyhedron describing a first Brillouin zone.

    ``vertices`` contains Cartesian reciprocal-space coordinates.  A face is
    a tuple of vertex indices in counter-clockwise order as viewed from
    outside.  ``halfspaces`` has the compact form ``[Gx, Gy, Gz, -|G|²/2]``
    and therefore represents ``halfspace[:3] · k + halfspace[3] <= 0``.
    """

    reciprocal_vectors: np.ndarray
    vertices: np.ndarray
    faces: tuple[tuple[int, ...], ...]
    edges: tuple[tuple[int, int], ...]
    halfspaces: np.ndarray
    facet_vectors: np.ndarray

    def __post_init__(self) -> None:
        vectors = np.asarray(self.reciprocal_vectors, dtype=float)
        vertices = np.asarray(self.vertices, dtype=float)
        halfspaces = np.asarray(self.halfspaces, dtype=float)
        facet_vectors = np.asarray(self.facet_vectors, dtype=float)
        vectors.setflags(write=False)
        vertices.setflags(write=False)
        halfspaces.setflags(write=False)
        facet_vectors.setflags(write=False)
        object.__setattr__(self, "reciprocal_vectors", vectors)
        object.__setattr__(self, "vertices", vertices)
        object.__setattr__(self, "halfspaces", halfspaces)
        object.__setattr__(self, "facet_vectors", facet_vectors)

    @property
    def volume(self) -> float:
        """Volume enclosed by the polyhedron in reciprocal space."""

        signed_volume = 0.0
        for face in self.faces:
            origin = self.vertices[face[0]]
            for index in range(1, len(face) - 1):
                first = self.vertices[face[index]]
                second = self.vertices[face[index + 1]]
                signed_volume += float(np.dot(origin, np.cross(first, second))) / 6.0
        return abs(signed_volume)

    @property
    def n_vertices(self) -> int:
        return len(self.vertices)

    @property
    def n_faces(self) -> int:
        return len(self.faces)

    def contains(self, points: Any, tolerance: float = 1e-9) -> np.ndarray | bool:
        """Test whether Cartesian reciprocal-space points lie in the zone."""

        array = np.asarray(points, dtype=float)
        scalar = array.ndim == 1
        if scalar:
            array = array[None, :]
        if array.ndim != 2 or array.shape[1] != 3:
            raise ValueError("points must have shape (3,) or (n, 3)")
        residual = array @ self.halfspaces[:, :3].T + self.halfspaces[:, 3]
        result = np.all(residual <= tolerance, axis=1)
        return bool(result[0]) if scalar else result

    is_inside = contains

    def face_polygons(self) -> list[np.ndarray]:
        """Return face coordinates, convenient for plotting."""

        return [self.vertices[list(face)] for face in self.faces]


def first_brillouin_zone(
    lattice: Lattice | Any,
    *,
    search: int = 2,
    tolerance: float = 1e-9,
) -> BrillouinZone:
    """Construct the first Brillouin zone of a direct or reciprocal basis.

    Parameters
    ----------
    lattice:
        A :class:`~brillouin_zone_toolkit.lattices.Lattice` or a reciprocal
        basis supplied directly as a ``(3, 3)`` array.  Arrays are interpreted
        as reciprocal vectors; use ``Lattice`` when starting from direct
        vectors.
    search:
        Integer coefficient radius used to enumerate reciprocal vectors.  A
        value of two is enough for SC, FCC, BCC and the default hexagonal
        examples.  Increase it for highly anisotropic custom cells.
    tolerance:
        Relative geometric tolerance used for plane and vertex tests.
    """

    if not isinstance(search, (int, np.integer)) or int(search) < 1:
        raise ValueError("search must be a positive integer")
    if tolerance <= 0 or not np.isfinite(tolerance):
        raise ValueError("tolerance must be a positive finite number")
    reciprocal_basis = _basis(lattice)
    all_points = _reciprocal_candidates(reciprocal_basis, int(search))
    # The shell with coefficients in {-1, 0, 1} already contains the
    # defining planes of the standard SC/FCC/BCC/hexagonal cells.  Instead of
    # intersecting every triple in a much larger shell, grow the constraint
    # set only when a farther reciprocal point actually cuts the current
    # polyhedron.  This preserves the explicit half-space algorithm while
    # keeping ``search=2`` inexpensive for the common examples.
    first_shell = _reciprocal_candidates(reciprocal_basis, 1)
    zone = _construct_zone(reciprocal_basis, first_shell, float(tolerance))
    if int(search) == 1:
        return zone
    remaining = all_points
    scale = max(1.0, float(np.max(np.linalg.norm(all_points, axis=1))))
    violation_tolerance = float(tolerance) * scale
    selected = first_shell.copy()
    for _ in range(int(search)):
        residual = remaining @ zone.vertices.T - 0.5 * np.einsum("ij,ij->i", remaining, remaining)[:, None]
        offenders = remaining[np.any(residual > violation_tolerance, axis=1)]
        if len(offenders) == 0:
            break
        selected = np.vstack((selected, offenders))
        zone = _construct_zone(reciprocal_basis, selected, float(tolerance))
        remaining = remaining[
            ~np.any(np.all(np.isclose(remaining[:, None, :], offenders[None, :, :], atol=1e-12), axis=2), axis=1)
        ]
    return zone
